### ISSUE TITLE
Missing character in your code app/code/Bafmaamy/FieldValidator/Plugin/OrderSourceLogger.php

### ISSUE THREAD

**Issue by EliseDressCodes** [bafmaamy/Magento-FieldValidator#1]
Hello,

I've just installed your extension, thank you :)

I'm just opening this issue to inform you that there's a typo in your code that's preventing us from compiling. It's in your app/code/Bafmaamy/FieldValidator/Plugin/OrderSourceLogger.php file, on line 95 before the catch, there's a “}” missing.

Hope you will change it !

**Comment by bafmaamy** [comment]
@EliseDressCodes yeap, thank you too, updated :) Actually "}" should be on line 65, closing the IF statement.
